name: Angelportfolios
favicon: null
layout_spectrum: 0.18490135134197772
typography_spectrum: 0.8217215489130467
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#9D2D3C'
    - '#DDE4DD'
    - '#BCAB47'
    - '#6B574B'
    - '#160600'
  brandStrength: 0.5959112492855638
  lightness: 0.32992237410508096
  saturation: 0.4462590452749282
  rhythmicContrast: 0.13233494176529348
purpose: []
